
const articles=[
    {
        id:1,
        category:"Training & Technique",
        title:"HOW TO IMPROVE YOUR FREESTYLE ARM STROKE!",
        description:"Improve your freestyle arm stroke to develop a more efficient stroke! Catch, pull, push and recovery, these are the four key phases in a freestyle ...",
        meta:"Written by: ARENA COACHES 17 February '21",
        fullDescription:"<h1>HOW TO IMPROVE YOUR FREESTYLE ARM STROKE</h1> <p>Begin the catch phase with your elbow high, use your forearm to pull downwards. When your hand passes beneath your shoulder, your head should begin to rotate so that you can breathe properly.</p><p>Continue the pull phase keeping your body in the right position and making sure your hand and arm are under your body and not alongside it. Try to catch as much water as possible with your forearm. Having completed the pull phase, the palm of your hand should be facing upwards. </p> <p>During the final push phase, your arm pushes backwards until it comes out of the water. During the recovery phase, raise your elbow and when your hand is halfway along your body rotate your head so that it is facing forwards again.  </p><p>As soon as your hand reaches your shoulder, rotate it forwards so that it is just touching the water and extend it out in front of you to complete the stroke. </p> ",
        image:"images/freestyle_arm_stroke.jpg"
    },
    {
        id:2,
        category:"Swim Tech",
        title:"ACTIVITY TRACKERS FOR SWIMMING (PART 2) – 5 QUESTIONS TO HELP YOU MAKE THE RIGHT CHOICE Swim Tech",
        description:"I have to confess: it took me longer than expected to get a proper grasp of what the market has to offer and what I myself really need (Do you …",
        meta:"Written by: FILIPPO ANTONIELLO 20 September '16",
        fullDescription:"I have to confess: it took me longer than expected to get a proper grasp of what the market has to offer and what I myself really need (Do you really need an Activity Tracker for swimming?) but, with your help, I have managed to clarify my thoughts and set myself a series of questions to let me make the right choice. 1. DESIGN OR FUNCTIONALITY? Some devices are really sexy-looking, like the waterproof Bluetooth earphones or The Dash products by Bragi, which even let you listen to music. The Withings Activité watch has a wonderful vintage design (starting with its fingers), so unusual for a “smart” object. Then there is the minimal design of Misfit Shine (that I have had for about a month now), which is now working in partnership with Speedo, so that it can record activity in the water. Nevertheless, as is often the case, design means accepting certain compromises and if you want the highest accuracy possible, at least in the case of swimming, you have to make some minor concessions in terms of aesthetics. 2. OPEN WATER OR THE POOL? What is the difference? A GPS is extremely important for open-water swimming, because it obviously allows you to set your own course in the water. Of course you cannot do that in indoor pools (there is no signal inside buildings).There are some excellent devices equipped with GPS that can also be worn in everyday life, but, unfortunately, they can be rather expensive. See the Garmin fēnix® 3 HR, Suunto Ambit3 Run or Polar V800, the top of the range in their category and loved by many triathletes. If you are willing to make some concessions, the TomTom Multi-Sport GPS Watch  is extremely functional and definitely has a more competitive price tag. These devices also work in the pool, but does it really make sense to spend so much money when you will not be using even a third of the functions? 3. IN A TEAM OR ON YOUR OWN? That is an easy one. Certain kinds of technology are only useful if you are part of a team with a coach who watches you swim. All the rest are “self-service”. Technology like Triton is designed to help coaches train their athletes more effectively, allowing them to monitor several different swimmers in the pool in real time. Avida Sports Swim Faster  works on the same principle but also allows real-time vocal feedback from the coach to the swimmer. In the UK various pools now offer SwimTag, a device you are given when you enter the water and then give back when you leave the pool. This means the user can access all their data online and even take part in online competitions.",
        image:"images/activity-tracker-2.jpg"
    },
    {
        id:3,
        category:"Swim Tech",
        title:"SWIM TO THE MUSIC",
        description:"As a “hardcore” swimmer I have never been particularly keen on anything other than a conventional swimming suit, swim cap and goggles. ...",
        meta:"Written by: ARENA COACHES 17 April '15 ",
        fullDescription:"As a “hardcore” swimmer I have never been particularly keen on anything other than a conventional swimming suit, swim cap and goggles. Nevertheless, because I am curious by nature, I decided to test out this new product and gain a closer insight into the world of swimming technology, trying out in the water something I was so familiar with as a triathlete/runner, i.e. listening to music while I swim. And even though I have always enjoyed “listening to” the water during my training sessions, I tried to replace  the sound of water with something with a more catchy beat. As we all know, music is extremely powerful and can affect our state of mind, summoning up our inner strength and helping us really focus. As I told you in “Mental strength”, music can send positive signals to the brain, reducing our perceived exertion and associating it with “positive” feelings. That is why so many athletes turn up at the starting blocks wearing their headphones and that is also why music is considered to be “doping” in other sports (i.e. running) and hence banned from races. Arena satisfied my sceptical curiosity by allowing me to test out its new waterproof Swimming Pro MP3 player. It has an eye-catching design and its ergonomic shape makes it easy to grip even with wet hands. It is also very compact in size with an easy-to-read screen.   Attached securely to my goggles for comfort purposes (but you can also attach it to your swim cap or suit), it did not bother me at all, because it is really light-weight. This is a real bonus, particularly during long training sessions. Incidentally, a “mini” version has recently been brought out that is even more comfortable because it is even smaller. So far so good, but the thing I was most curious about was to see how comfortable and hard-wearing the earphones are while swimming. Due to my physical build I have always had problems with earphones, because they never fit my ears properly, they move around and can be really bothersome in the long run. Fortunately, and due to Arena’s expertise, Swimming Pro waterproof earphones fit me perfectly and are not bothersome at all, allowing me to focus solely on my swim stroke. Of course it will take some time to get used to them, but I am convinced that this little gadget will become a faithful training partner.",
        image:"images/Mp3_mini.jpg"
    },
    {
        id:4,
        category:"Swim Tech",
        title:"WHAT IS THE SPEKTRO GLIDE?",
        description:"Andrea Di Nino is Head Coach and Technical Director of A.D.N Swim Project, the first European program for international swimmers. The mission ...",
        meta:"Written by: ANDREA DI NINO 6 November '15",
        fullDescription:"The Spektro machine is a device that allows the athlete to obtain overspeed (go beyond their natural limit) and resistance speed in the water, depending on the kind of set they are undertaking. The swimmer is able to replicate close to, or even up to race speed as many times as required in any given session, which is almost impossible to achieve otherwise, even with the assistance of paddles and fins. If you have an athlete who is swimming 2.00m/s during competition for instance, but is looking to bring their time down to 2.05m/s, the machine can be set at 2.05m/s, allowing the athlete to feel and understand the correct body position needed to achieve the speed. In terms of power, it is the same as the swim with parachute (adjustable belt connected to a durable parachute), but the only difference is that you can set it up exactly to the resistance you want, which is a lot more accurate than the three/fourth option setting the parachute system allows. An individual database is held for each swimmer, making it easy for the coach to compare performance by month, year or even Olympic cycle. This data is incredibly accurate and allows the coach to understand exactly where power is held or lost. Thanks to this information, the coach has a clear understanding on what needs to be worked on (speed, power or glide), therefore making it easier to reach specific goals.",
        image:"images/streamline1.jpg"
    },
    {
        id:6,
        category:"Training & Technique",
        title:"OPEN WATER SWIMMING: TIPS FROM FABRIZIO ANTONELLI, GREGORIO",
        description:"Considering what is happening at the moment, lots of swimmers are considering training more (or starting to train) in open water. Here are som...",
        meta:"Written by: ARENA 4 June '20",
        fullDescription:"<h3>What fundamentals do you need to master and train?</h3><p>From the viewpoint of technique, freestyle is the preferred stroke due to the simple fact that it is less energy consuming to swim freestyle at any given speed compared to other strokes, so you need to focus on your freestyle swim stroke.</p><p>As regards any adjustments compared to swimming in the pool, I think the most interesting thing is how to adapt our swim stroke to the conditions we encounter.</p><p>This is a key factor both for top-level swimmers and amateurs taking to the open waters for the first time, because the weather/water conditions can change at any moment: this means you have to work hard on your proprioceptive skills so you can master and control your swim stroke properly both in terms of making “technical adjustments” to strengthen or lengthen your stroke and from a coordination viewpoint. That is because it can be useful to be able to adapt your stroke to the sea/open water conditions in which you are racing or training.</p><p>So, even though you are still swimming freestyle, changing your coordination, speeding up/slowing down your leg kick or altering your stroke rate are very important factors that can make a real difference.</p>",
        image:"images/ow_antonelli.jpg"
    },
    {
        id:7,
        category:"Training & Technique",
        title:"HOW TO IMPROVE YOUR UNDERWATER PHASE",
        description:"The underwater phase is swimming’s fifth stroke. To improve this aspect of your swimming, you must glide through the water with perfect ...",
        meta:"Written by: ARENA COACHES 18 May '20",
        fullDescription:"<h3>The underwater phase is considered to be a vital part of any swim stroke. What is the key to performing it properly?</h3><p>The first key to a perfect underwater phase is keeping your body perfectly streamlined under the surface of the water. Keep your head between your shoulders and your arms fully extended out in front.</p><h3>And then what?</h3><p>After pushing off, glide under the surface of the water for a few seconds and begin to move your hips and legs without bending your back excessively.</p><p>The movement should begin from your hips and continue along your legs, coordinating your legs lift and kick. Make sure your upper body is fully extended in the right position.</p><p>Your leg kick should initially be deep and powerful, gradually speeding up with quicker. shallower movements. </p><p>Powerfin and Powerfin Pros are an excellent means of improving your underwater phase: they will help you control your body movement and allow you to feel the water better.</p>",
        image:"images/underwater.jpg"
    },
    {
        id:8,
        category:"A Swimmer's life",
        title:"WHY DO YOU SWIM?",
        description:"There are many reasons why we take part in our favourite sport. Some people want to keep fit, others want to train with their old friends, and yet ...",
        meta:"Written by: ARENA 23 December '20 ",
        fullDescription:"<h1>There are many reasons why we take part in our favourite sport.</h1><h2>Some people want to keep fit, others want to train with their old friends, and yet others want to prove they are the best. Everybody has their own reason.</h2><p>In psychology, motivation tends to be divided into intrinsic motivation (“I swim because I love swimming”) or extrinsic motivation (“I swim to be a winner.”). As well as being qualitatively different, motivation can also vary quantitively from person to person. So, there are cases of people with absolutely no motivation (unmotivated athlete) and others with a very high level of motivation. Plenty of research has shown there is a correlation between having a high level of intrinsic motivation and a long career in sport.</p><p>According to one of the most important theories about motivation, i.e. self-determination theory (Deci and Ryan, 2000), there are three basic needs we all focus on and that indicate the presence of intrinsic motivation.</p><h6>These three needs are:</h6><ul><li>the need for autonomy;</li><li>the need for competence;</li><li>the need for relatedness.</li></ul>",
        image:"images/why_do_you_swim_blog.jpg"
    },
    {   id:9,
        category:"A Swimmer's life",
        title:"GOAL SETTING DURING LOCKDOWN",
        description:"Lockdown has required a lot of swimmers to press ‘Pause’ on their athletic ambitions. While training and competitions continue to be cancelled ...",
        meta:"Written by: BRADLEY CROCKER 24 March '21 ",
        fullDescription:"<h1>CREATE A CONNECTION BETWEEN YOUR TRAINING AND YOUR GOALS</h1><p>It’s easy to just mindlessly go through the motions of an exercise. This likely won’t lead to quality workouts, though, and it certainly won’t foster internal motivation. It’s therefore important to understand how your training is connected to a goal that you’ve set.</p><p>Say your objective during the pandemic is to be physically active in order to maintain a base level of fitness. Most forms of fitness will do the trick here, so you can get creative in finding fun activities that will get your heart rate up.</p><p>If you have instead decided (in cooperation with your coach) to strive for a more elite level of fitness over lockdown, then your remote training will need to be more rigorous. All workouts should be designed to nurture your development as an athlete, and you must understand how each exercise will transfer to progress in the water.</p>",
        image:"images/SPORTSWEAR-SHOOT-RICCIONE-2018.jpg"
    },
    {
        id:10,
        category:"Fitness & Wellness",
        title:"THE IMPORTANCE OF HYDRATION FOR SWIMMERS",
        description:"Hydration for swimmers is perhaps one of the most underestimated aspects. Find out what, how much and when it is important for a swimmer ...",
        meta:"Written by: MANUELE TREZZI 17 March '21 ",
        fullDescription:"<h1>Find out what, how much and when it is important for a swimmer to drink!</h1><p>Bearing in mind that most weight loss during training is mainly in the form of liquids, it is obvious how important it is to reintegrate what you have lost. It is particularly overlooked in swimming because, compared to other sports, you do not realise how much liquid you lose in the pool.</p><p>For example, you sweat and feel hot when you go for a run or play football: the logical consequence of this is to drink cold water, even just to cool yourself down.</p><p>You do not feel like you are sweating when you swim, but you lose liquids just the same, for example by producing more urine. That is why you are more likely to suffer from dehydration problems.</p><p>INADEQUATE LEVELS OF HYDRATION FOR SWIMMERS: WHAT KIND OF PROBLEMS ARE WE TALKING ABOUT? The most obvious problem is the greater likelihood of suffering from cramps. Creating a water imbalance disrupts the process of muscle contraction and, hence, results in cramps.</p><p>This can also cause sudden changes in body temperature, cardiac stress and a feeling of weakness. This inevitably means that failing to hydrate before/during/after physical exercise can affect your performance.</p><h2>ALL THIS CAN BE AVOIDED IN TWO WAYS</h2><ul><li>Firstly, just keep hydrated throughout the day</li><li>Secondly, always have at least a half-litre (or, better still, one-litre) water bottle with you at the poolside.</li></ul>",
        image:"images/hydration_swimming2.jpg"
    },
    {
        id:11,
        category:"Insider Advice",
        title:"TIPS FOR CHOOSING THE RIGHT LENSES FOR YOUR GOGGLES",
        description:"How to choose lenses for arena goggles The lenses for arena goggles are not all the same. Choose the ideal style and colour for your specific ...",
        meta:"Written by: ARENA 23 November '15",
        fullDescription:"<h1>WHICH GOGGLES SHOULD I CHOOSE FOR OUTDOOR SWIMMING?</h1><p>If you swim outdoors, particularly in open water, you should choose goggles with mirror lenses that reflect light and minimise the amount of light getting in your eyes.</p><ul>Mirror lenses for arena goggles come in various colours.<li>DARK LENSES: if the sun is extremely strong or bright, our advice is to choose dark-coloured mirror lenses, for example “blue” or “silver”, which will prevent any reverberation effect and keep the sun out of your eyes.</li><li>CLEAR LENSES: choose clear-coloured mirror lenses, for example a “copper” colour, for cloudy days when the sun is not so bright or when swimming early in the morning or late in the afternoon. The mirror effect is the same as with dark lenses, but the clear colour provides increased visibility in dim light.</li></ul>",
        image:"images/swipe_range1.jpg"
    },
    {
        id:12,
        category:"Just for Women",
        title:"WATERPROOF MAKEUP: FACT OR FICTION?",
        description:"Some waterproof makeup products are really only resistant to sweat, tears and the occasional splash, but others actually work for swimming.  ...",
        meta:"Written by: ARENA 27 May '17",
        fullDescription:"<h3>Some waterproof makeup products are really only resistant to sweat, tears and the occasional splash, but others actually work for swimming.</h3><p>Have you ever worn makeup swimming and ended up a streaky, panda-eyed mess? Clearly, not all supposedly waterproof products are created equal, but is there makeup that works?</p><p>Some people wonder why you would ever want to swim with makeup on. Why not just wash it off before you get in the water and reapply afterward? Well, some women don’t want to take the time, especially if they’re just going for a quick workout during lunch and need to be presentable immediately afterward. And some women simply feel better and more ready to face the world in makeup, even at the pool.</p><p>So is it possible to swim in makeup and not come out looking ridiculous? Yes, but you’ll probably have to do some experimenting. Everyone’s face is different and will react to different products in different ways.</p><p>Waterproof mascara is the most ‘mainstream’ waterproof product on the market, though often it’s designed to withstand mere tears rather than a full swim workout. And some waterproof products flake off or dry out your lashes, or make your lashes feel stiff and breakable. Ask 10 swimmers for their favourite waterproof mascara and you’ll likely get 10 different answers (though some products, like the Urban Decay Cannonball Ultra Waterproof Mascara, Eyeko Sport Waterproof Mascara, and Dior Diorshow Waterproof Mascara, do make frequent repeat showings in ‘best of’ lists).</p><p>Going beyond mascara, you could do worse than look to synchronized swimming for help. Have you ever wondered how synchronized swimmers’ makeup (and hair!) stands up to the stress of their gruelling routines? In synchronized swimming competitions, the swimmers wear heavy makeup so that the judges can see their expressions from far away; otherwise the ‘artistic impression’ component of their score would suffer. Synchronized swimmers are sometimes compared to burlesque performers, and it’s true that it can be harder to create a natural look than a bold look, but you can still use some of the same products, just less excessively.</p>",
        image:"images/waterproof_makeup.jpg"
    }
]

export default articles